### ISSUE TITLE
"gutterpreview.paths"

### ISSUE THREAD

**Issue by ccaioccesar** [kisstkondoros/gutter-preview#110]
Is possible to set a path to search for the images?

I tried both ways above:

```
    "gutterpreview.sourceFolder": "C:/Users/CAIO/Documents/Github/images/",

    "gutterpreview.paths": {
        
        "@assets/*": ["C:/Users/CAIO/Documents/Github/images/"],
    },
```
But it still doesn't recognize the images, only are recognized if they are on the same folder of the script.

**Comment by ccaioccesar** [comment]
Or is possible to change the path where it search for the image ?
I mean... instead search the image in the script folder, search in another defined folder.

Then we could use just the image name "x.png" instead of the entire path as the image is not in the same folder than the script.

**Comment by kisstkondoros** [comment]
Absolute paths were not supported for  "gutterpreview.sourceFolder" correctly. It is fixed in 0.29.0, which was just released.

**Comment by Miko321** [comment]
@kisstkondoros how to use `"gutterpreview.sourceFolder"`? 
I tried adding in my settings.json:
`"gutterpreview.sourceFolder": "C:/Users/Aru/Documents/Adobe/dynamiclinkmediaserver/",`

Then I have added in the script I'm working `picture.png` (that is inside of the folder path above), and when I hover it still don't find any picture.

**Comment by Miko321** [comment]
@kisstkondoros forgot to mention, I'm using win10 and the version you mentioned 0.29.0

**Comment by ccaioccesar** [comment]
I had forgotten about this issue I could see an answer 1year later 😅
@Miko321 I also could not get it working here even using the new version 0.29

I will open a new issue, maybe it's easier for @kisstkondoros to see it.
